#!/usr/bin/env bash
# One-time setup: permanent Cloudflare Tunnel with your own domain.
# Result: fixed https://jarvis.yourdomain.com (never changes).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

PORT="${JARVIS_PORT:-8765}"
TUNNEL_NAME="${JARVIS_TUNNEL_NAME:-jarvis-pwa}"
CF_DIR="${HOME}/.cloudflared"
CF_CONFIG="${CF_DIR}/config.yml"

if ! command -v cloudflared >/dev/null 2>&1; then
  echo "Install cloudflared first:  brew install cloudflared"
  exit 1
fi

echo ""
echo "  Permanent JARVIS HTTPS URL (Cloudflare Named Tunnel)"
echo "  ────────────────────────────────────────────────────"
echo ""
echo "  You need:"
echo "    • A domain added to Cloudflare (free plan is fine)"
echo "    • A subdomain, e.g. jarvis.yourdomain.com"
echo ""
echo "  After setup:"
echo "    • URL never changes (no more trycloudflare.com)"
echo "    • Set Netlify env JARVIS_API_URL=https://your-subdomain"
echo "    • Run ./scripts/install-autostart.sh — starts on Mac login"
echo ""

read -r -p "Subdomain to use (e.g. jarvis.yourdomain.com): " HOSTNAME
HOSTNAME="$(echo "$HOSTNAME" | tr -d ' ')"
if [ -z "$HOSTNAME" ]; then
  echo "Hostname required."
  exit 1
fi

PUBLIC_URL="https://${HOSTNAME}"

echo ""
echo "Step 1/4 — Log in to Cloudflare (browser will open) ..."
cloudflared tunnel login

echo ""
echo "Step 2/4 — Create tunnel '${TUNNEL_NAME}' ..."
if cloudflared tunnel list 2>/dev/null | grep -q "^${TUNNEL_NAME} "; then
  echo "  Tunnel '${TUNNEL_NAME}' already exists."
else
  cloudflared tunnel create "$TUNNEL_NAME"
fi

TUNNEL_ID="$(cloudflared tunnel list 2>/dev/null | awk -v n="$TUNNEL_NAME" '$2 == n { print $1; exit }')"
if [ -z "$TUNNEL_ID" ]; then
  echo "Could not find tunnel ID for ${TUNNEL_NAME}."
  exit 1
fi

CREDS="${CF_DIR}/${TUNNEL_ID}.json"
if [ ! -f "$CREDS" ]; then
  echo "Missing credentials file: $CREDS"
  exit 1
fi

echo ""
echo "Step 3/4 — DNS route ${HOSTNAME} → tunnel ..."
cloudflared tunnel route dns "$TUNNEL_NAME" "$HOSTNAME" || true

mkdir -p "$CF_DIR"
cat > "$CF_CONFIG" <<EOF
# JARVIS PWA — generated by scripts/setup-named-tunnel.sh
tunnel: ${TUNNEL_ID}
credentials-file: ${CREDS}

ingress:
  - hostname: ${HOSTNAME}
    service: http://127.0.0.1:${PORT}
  - service: http_status:404
EOF

mkdir -p "$ROOT/data"
echo "$PUBLIC_URL" > "$ROOT/data/public_url.txt"
echo "$TUNNEL_NAME" > "$ROOT/data/tunnel-name.txt"
echo "$HOSTNAME" > "$ROOT/data/tunnel-hostname.txt"

echo ""
echo "Step 4/4 — Saved configuration."
echo ""
echo "════════════════════════════════════════════════════════════"
echo "  Permanent backend URL:"
echo ""
echo "    ${PUBLIC_URL}"
echo ""
echo "  Next steps:"
echo "    1. Netlify → Site settings → Environment variables"
echo "       JARVIS_API_URL = ${PUBLIC_URL}"
echo "    2. Redeploy Netlify (auto-connect, no URL prompt)"
echo "    3. ./scripts/install-autostart.sh"
echo "════════════════════════════════════════════════════════════"
echo ""
