"""Open Word or Excel and compose content visibly on screen."""

from __future__ import annotations

import platform
import re
import subprocess
import time
from pathlib import Path

from actions.open_app import open_app
from core.ollama_text import ollama_complete

_SYSTEM = platform.system()


def _generate_word_content(topic: str, word_count: int, title: str = "") -> str:
    title_bit = f"Title: {title}\n" if title else ""
    prompt = (
        f"Write a clear, well-structured document about: {topic}\n"
        f"Target length: about {word_count} words.\n"
        f"{title_bit}"
        "Use plain paragraphs only — no markdown, no bullet symbols, no headings with #.\n"
        "Start with a short title line if no title was given, then the body."
    )
    tokens = max(120, min(900, int(word_count * 1.6)))
    return ollama_complete(prompt, max_tokens=tokens).strip()


def _generate_excel_rows(topic: str, rows: int = 8) -> list[list[str]]:
    prompt = (
        f"Create spreadsheet data about: {topic}\n"
        f"Return exactly {rows} data rows plus a header row as CSV.\n"
        "Use commas only as separators. No quotes unless necessary. 3-5 columns."
    )
    raw = ollama_complete(prompt, max_tokens=400)
    lines = [ln.strip() for ln in raw.splitlines() if ln.strip() and "," in ln]
    if not lines:
        return [["Topic", "Detail"], [topic, "Generated by JARVIS"]]
    out: list[list[str]] = []
    for ln in lines[: rows + 1]:
        out.append([c.strip() for c in ln.split(",")])
    return out


def _escape_keystroke(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def _run_applescript(script: str) -> bool:
    try:
        r = subprocess.run(
            ["osascript", "-e", script],
            capture_output=True,
            text=True,
            timeout=30,
        )
        return r.returncode == 0
    except Exception:
        return False


def _type_chunks_mac(text: str, chunk_words: int = 6, pause: float = 0.12) -> None:
    """Type text in small chunks so the user can see it appear."""
    words = text.split()
    if not words:
        return
    for i in range(0, len(words), chunk_words):
        chunk = " ".join(words[i : i + chunk_words])
        if i + chunk_words < len(words):
            chunk += " "
        safe = _escape_keystroke(chunk)
        _run_applescript(f'tell application "System Events" to keystroke "{safe}"')
        time.sleep(pause)
    _run_applescript('tell application "System Events" to key code 36')  # Return


def _compose_word_mac(content: str, title: str = "") -> str:
    open_app(parameters={"app_name": "word"}, response=None, player=None)
    time.sleep(2.0)
    _run_applescript(
        'tell application "Microsoft Word" to activate\n'
        "tell application \"Microsoft Word\"\n"
        "  if (count of documents) = 0 then make new document\n"
        "end tell"
    )
    time.sleep(0.8)

    if title:
        _type_chunks_mac(title, chunk_words=4, pause=0.15)
        _run_applescript('tell application "System Events" to key code 36')
        time.sleep(0.2)

    paragraphs = [p.strip() for p in re.split(r"\n\s*\n", content) if p.strip()]
    if not paragraphs:
        paragraphs = [content]

    for para in paragraphs:
        _type_chunks_mac(para, chunk_words=5, pause=0.1)
        time.sleep(0.25)

    return f"Opened Word and typed about {len(content.split())} words, sir."


def _compose_excel_mac(rows: list[list[str]]) -> str:
    open_app(parameters={"app_name": "excel"}, response=None, player=None)
    time.sleep(2.0)
    _run_applescript(
        'tell application "Microsoft Excel" to activate\n'
        "tell application \"Microsoft Excel\"\n"
        "  if (count of workbooks) = 0 then make new workbook\n"
        "end tell"
    )
    time.sleep(0.8)

    for row in rows:
        for ci, cell in enumerate(row):
            if ci > 0:
                _run_applescript('tell application "System Events" to key code 48')  # Tab
                time.sleep(0.05)
            _type_chunks_mac(str(cell), chunk_words=3, pause=0.08)
        _run_applescript('tell application "System Events" to key code 36')
        time.sleep(0.15)

    return f"Opened Excel and entered {len(rows)} rows, sir."


def _fallback_save_and_open(app: str, content: str, topic: str) -> str:
    out_dir = Path.home() / "Documents" / "JARVIS"
    out_dir.mkdir(parents=True, exist_ok=True)
    safe = re.sub(r"[^\w\s-]", "", topic or "document")[:40].strip() or "document"
    if app == "excel":
        path = out_dir / f"{safe}.csv"
        path.write_text(content if "," in content else f"Topic,Notes\n{topic},{content}\n")
        subprocess.run(["open", str(path)], check=False)
        return f"Created {path.name} and opened it, sir."
    path = out_dir / f"{safe}.txt"
    path.write_text(content, encoding="utf-8")
    subprocess.run(["open", "-a", "Microsoft Word", str(path)], check=False)
    return f"Created {path.name} and opened in Word, sir."


def office_compose(parameters: dict | None = None, response=None, player=None) -> str:
    params = parameters or {}
    app = (params.get("app") or params.get("application") or "word").lower().strip()
    topic = (params.get("topic") or params.get("subject") or "").strip()
    title = (params.get("title") or "").strip()
    content = (params.get("content") or params.get("body") or "").strip()
    word_count = int(params.get("word_count") or params.get("words") or 300)

    if not content and not topic:
        return "I need a topic or content to compose, sir."

    if player and hasattr(player, "write_log"):
        player.write_log(f"SYS: Composing in {app}…")

    if app in ("excel", "spreadsheet", "sheet"):
        if _SYSTEM == "Darwin":
            rows = _generate_excel_rows(topic or title or "data")
            return _compose_excel_mac(rows)
        csv_text = "\n".join(",".join(r) for r in _generate_excel_rows(topic or "data"))
        return _fallback_save_and_open("excel", csv_text, topic or title)

    if not content:
        content = _generate_word_content(topic, word_count, title)
    if not content or content.startswith("(Could not"):
        return "I couldn't generate the document text, sir."

    if _SYSTEM == "Darwin":
        return _compose_word_mac(content, title or topic)

    return _fallback_save_and_open("word", content, topic or title)
